# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rsimsimd_wrappers", use_symbols = TRUE, package_name = "rsimsimd")

#' @usage NULL
#' @useDynLib rsimsimd, .registration = TRUE
NULL

get_capabilities_rs <- function() .Call(wrap__get_capabilities_rs)

dist_cosine_rs <- function(vec_a, vec_b) .Call(wrap__dist_cosine_rs, vec_a, vec_b)

dist_cosine_single_mult_rs <- function(vec, mat) .Call(wrap__dist_cosine_single_mult_rs, vec, mat)

dist_cosine_mult_mult_rs <- function(mat_a, mat_b) .Call(wrap__dist_cosine_mult_mult_rs, mat_a, mat_b)

dist_cosine_mat_rs <- function(mat) .Call(wrap__dist_cosine_mat_rs, mat)


# nolint end
