# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rsimsimd_wrappers", use_symbols = TRUE, package_name = "rsimsimd")

#' @usage NULL
#' @useDynLib rsimsimd, .registration = TRUE
NULL

get_capabilities_rs <- function() .Call(wrap__get_capabilities_rs)

dist_cosine_rs <- function(vec_a, vec_b) .Call(wrap__dist_cosine_rs, vec_a, vec_b)

dist_cosine_single_mult_rs <- function(vec, ll) .Call(wrap__dist_cosine_single_mult_rs, vec, ll)

dist_cosine_mult_mult_rs <- function(ll_a, ll_b) .Call(wrap__dist_cosine_mult_mult_rs, ll_a, ll_b)

dist_cosine_mat_rs <- function(ll) .Call(wrap__dist_cosine_mat_rs, ll)


# nolint end
